using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SMP
{
    public partial class BuyersTable : Form
    {
        DB_SMPEntities1 db = new DB_SMPEntities1();
        frm_Add frm_buyers = new frm_Add();
        Buyer buyer_table = new Buyer();
       
        //BuyersTable buyer_table = new BuyersTable();
        public int id;
        public BuyersTable()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            buyersTableAdapter1.Fill(dB_SMPDataSet1.Buyers);
        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            frm_buyers.ShowDialog();
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
        void Update_data()
        {
            db = new DB_SMPEntities1();
            gridControl1.DataSource = db.Buyers.ToList();
        }
        private void btn_renew_Click(object sender, EventArgs e)
        {
            Update_data();
        }
        
        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Buyer del = new Buyer();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("Id"));
            var res = MessageBox.Show("هل انت متأكد من الحذف", "الحذف", MessageBoxButtons.YesNo);
            if (res == DialogResult.Yes)
            {
                del = db.Buyers.Where(s => s.Id == id).FirstOrDefault();
                db.Buyers.Remove(del);
                db.SaveChanges();
                toast.labl_caption.Text = "تم حذف الصنف بنجاح";
                toast.Show();
                this.Close();
                Update_data();
            }

            else
            {
                MessageBox.Show("قم بتحديد للحذف ");
            }
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            frm_Add edit = new frm_Add();

            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("Id"));
            Buyer edited = db.Buyers.Where(x => x.Id == id).FirstOrDefault();
            edit.txtid.Text = edited.Id.ToString();
            edit.txtitemName.Text = edited.name;
            edit.txtSuppliersName.Text = edited.SuppliersName;
            edit.dateTimePicker1.Value = DateTime.Parse(edited.BuyingDate.ToString());
            edit.txtSell.Text = Convert.ToDouble(edited.SellingPrice).ToString();
            edit.numericUpDown1.Value = int.Parse(edited.itemsNumbers.ToString());
            edit.txtBuy.Text = Convert.ToDouble(edited.BuyingPrice).ToString();
            edit.txtTotalPrice.Text = Convert.ToDouble( edited.Profit).ToString();
           


            edit.BtnAdd.Text = "تعديل";
            edit.Show();
            this.Close();



        }
    }
}
