//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> itemNumber { get; set; }
        public string SuppliersName { get; set; }
        public Nullable<System.DateTime> BuyingDate { get; set; }
        public Nullable<double> BuyingPrice { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<int> itemsNumbers { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> SuppId { get; set; }
    
        public virtual TB_CAT TB_CAT { get; set; }
        public virtual TB_SUP TB_SUP { get; set; }
    }
}
