using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace SMP
{
    public partial class FRM_CAT : Form
    {
        DB_SMPEntities1 db = new DB_SMPEntities1();
        TB_CAT tb_cat = new TB_CAT();
        int id;
        public FRM_CAT()
        {
            InitializeComponent();
          
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            SMP.DB_SMPEntities1 dbContext = new SMP.DB_SMPEntities1();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_CAT.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControl1.DataSource = dbContext.TB_CAT.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        //add
        private void btn_add_Click(object sender, EventArgs e)
        {
            FRM_CAT_ADD frm_add = new FRM_CAT_ADD();
            frm_add.id = 0;
            frm_add.btn_add.Text = "اضافة";
            frm_add.Show();
        }

        //renew
        private void btn_renew_Click(object sender, EventArgs e)
        {
            update_data();
        }

        //delete

        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            try
            {
                id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
                var res = MessageBox.Show("هل انت متاكد من عملية الحذف", "حذف", MessageBoxButtons.YesNo);
                if (res == DialogResult.Yes)
                {
                    tb_cat = db.TB_CAT.Where(x => x.ID == id).FirstOrDefault();
                    db.Entry(tb_cat).State = EntityState.Deleted;
                    db.SaveChanges();
                    toast.labl_caption.Text = "تم حذف الصنف بنجاح";
                    toast.Show();
                    this.Close();
                    //renew tale
                    update_data();
                }
            }
            catch
            {
                MessageBox.Show("قم بالتحديد لحذف الصنف");
            }
          
           
        }
        //renew function
        private void update_data()
        {
            Toast toast = new Toast();

            var w = tb_cat = db.TB_CAT.Where(x => x.ItemQuantity <= 0).FirstOrDefault();
            toast.labl_caption.Text = "(" + w.CAT_Name + ")" + "\t لا يوجد كمية من هذا الصنف ";
            toast.Show();
            db = new DB_SMPEntities1();
           gridControl1.DataSource = db.TB_CAT.ToList();
        }
        //edit
        private void btn_edit_Click(object sender, EventArgs e)
        {
            FRM_CAT_ADD frm_add = new FRM_CAT_ADD();
           id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
           
            tb_cat = db.TB_CAT.Where(x => x.ID == id).FirstOrDefault();
            frm_add.txt_name.Text = tb_cat.CAT_Name.ToString();
            frm_add.txt_price_buy.Text = tb_cat.CAT_Price_buy.ToString();
            frm_add.txt_price_sell.Text=tb_cat.CAT_Price_sale.ToString();
            frm_add.id = id;
            frm_add.btn_add.Text = "تعديل";
            frm_add.Show();
        }

       

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }
    }
}
