using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SMP
{
    public partial class Pn_SellTable : Form
    {
        DB_SMPEntities1 db = new DB_SMPEntities1();
        SellsAdd sellsadd = new SellsAdd();
        Sell tb_sell = new Sell();
        public int id;
        public Pn_SellTable()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //sellsTableAdapter1.Fill(salePipesDataSet11.Sells);
            // This line of code is generated by Data Source Configuration Wizard
            // sellsTableAdapter2.Fill(salePipesDataSet12.Sells);
            // This line of code is generated by Data Source Configuration Wizard
            //sellsTableAdapter1.Fill(salePipesDataSet21.Sells);
            // This line of code is generated by Data Source Configuration Wizard
            sellsTableAdapter1.Fill(dB_SMPDataSet41.Sells);
        }

        private void Pn_SellTable_Load(object sender, EventArgs e)
        {

        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            
        }

        private void btnAdd_Click_1(object sender, EventArgs e)
        {
            
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            sellsadd.ShowDialog();
        }
        void Update_data()
        {
         //   db = new DB_SMPEntities1();
            gridControl1.DataSource = db.Sells.ToList();
        }

        private void btn_renew_Click(object sender, EventArgs e)
        {
            Update_data();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Sell del = new Sell();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("Id"));
            var res = MessageBox.Show("هل انت متأكد من الحذف", "الحذف", MessageBoxButtons.YesNo);
            if (res == DialogResult.Yes)
            {
                del = db.Sells.Where(s => s.Id == id).FirstOrDefault();
                db.Sells.Remove(del);
                db.SaveChanges();
                toast.labl_caption.Text = "تم حذف الصنف بنجاح";
                toast.Show();
                this.Close();
                Update_data();
            }

            else
            {
                MessageBox.Show("قم بتحديد للحذف ");
            }
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            SellsAdd frm_add = new SellsAdd();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("Id"));
            tb_sell = db.Sells.Where(x => x.Id == id).FirstOrDefault();
            tb_sell.Id = id;
            frm_add.txtid.Text = tb_sell.Id.ToString();
            frm_add.txtItemName.Text = tb_sell.ItemName.ToString();
            frm_add.TxtCustomerName.Text= tb_sell.CustomerId.ToString();
            frm_add.txtSell.Text = tb_sell.SellPrice.ToString();
            frm_add.txtTotalPrice.Text = tb_sell.TotalPrrice.ToString();
            frm_add.numericUpDown1.Value = int.Parse(tb_sell.SellQuantity.ToString());
            frm_add.txtSellDate.Value = DateTime.Parse( tb_sell.SellDate.ToString());
            frm_add.Show();
            frm_add.BtnAdd.Text = "تعديل";
            db.Entry(tb_sell).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
        }
    }
    }

