//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> SellDate { get; set; }
        public string CustomerId { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<int> SellQuantity { get; set; }
        public Nullable<double> TotalPrrice { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> CatId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual TB_CAT TB_CAT { get; set; }
    }
}
