//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Users
    {
        public string User_Name { get; set; }
        public string User_Password { get; set; }
        public string User_Rol { get; set; }
        public string User_State { get; set; }
        public int ID { get; set; }
    }
}
